services:
  # MariaDB 資料庫
  mariadb:
    image: mariadb:11.2
    container_name: exchange-rate-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exchange_rate_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      TZ: Asia/Taipei
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - exchange-rate-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Spring Boot 應用程式
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exchange-rate-app
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: exchange_rate_db
      DB_USER: appuser
      DB_PASSWORD: apppassword
      SERVER_PORT: 8080
      TZ: Asia/Taipei
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - exchange-rate-network
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local

networks:
  exchange-rate-network:
    driver: bridge