spring:
  application:
    name: exchange-rate-project

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:exchange_rate_db}?serverTimezone=Asia/Taipei&characterEncoding=UTF-8
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.example.exchangerate: DEBUG
    org.hibernate.SQL: DEBUG